name: lucas_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:

  flutter_typeahead: ^3.2.4
  money2: ^3.1.2
  url_launcher: ^6.0.18
  flutter_svg: ^1.0.3
  image_network: ^2.4.0
  cloud_firestore: ^3.1.8
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.7
  image_picker: ^0.8.4+9
  file: ^6.1.2

  auto_size_text: ^3.0.0

  editable: ^2.0.0

  xfile: ^1.1.0

  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.3.1

  material_floating_search_bar: ^0.3.6

  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/
